# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install jdk
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - name: permit
      run: chmod +x gradlew
    - name: build
      run: ./gradlew build
    - name: pwd
      run: pwd
    - name: check build
      run: ls /home/runner/work/dev/dev/build/libs
      
    - name: Set up Docker Buildx 
      uses: docker/setup-buildx-action@v1 
    - name: docker ps
      run: docker ps
    - name: dockerfile
      run: cp /home/runner/work/dev/dev/build/libs ./Dockerfile
    - name: Build and push 
      uses: docker/build-push-action@v2
      id: docker_build
      with: 
        push: true 
        tags: dawun4705/m-dev:cicd_tomcat_v1
