# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Gradle

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: install jdk
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 11
        cache: gradle
    - name: permit
      run: |
        chmod +x gradlew
        ./gradlew build
        ls ./build/libs
      
    - name: Set up Docker Buildx 
      uses: docker/setup-buildx-action@v1 
      
    - name: docker ps
      run: docker ps
      
    - name: docker build
      run: |
        cp ./build/libs/*.war ./Dockerfile
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_${GITHUB_RUN_NUMBER}	./Dockerfile
        docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest ./Dockerfile
        docker images
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: docker push
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/m-dev:tomcat_latest
      
    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_ServiceAccount_KEY }}
        
    - name: Get GKE Credentials
      uses: google-github-actions/get-gke-credentials@v0.7.0
      with:
        cluster_name: uni
        location: us-central1-c
        project_id: daun-343400
  
    - name: was-deploy restart
      run: kubectl rollout restart deployment was
    
    - name: mv .war
      run: mv ./build/libs/my-spring-board-0.0.1-SNAPSHOT.war ./build/libs/`date +%Y%m%d%H%M`.war
    - id: upload
      uses: google-github-actions/upload-cloud-storage@v0
      with:
        path: ./build/libs/
        destination: hidaun
        parent: false
        glob: '*.war'
